title: Prince Martin Books by Brandon Hale
description: Boys will love the Prince Martin Epic illustrated chapter book series about Martin, the brave boy prince.
baseurl: ""
asset_version: "20260213"
